import { NgModule } from '@angular/core';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';
import { AuthGuard } from './guards/auth.guard';
import { GiphyService } from "./api/giphy.service";
import { HttpClientModule } from "@angular/common/http";


const routes: Routes = [
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: 'home', loadChildren: () => import('./home/home.module').then( m => m.HomePageModule)},
  { path: 'categorias', loadChildren: './categorias/categorias.module#CategoriasPageModule', },
  { path: 'cat-abecedario', loadChildren: './cat-abecedario/cat-abecedario.module#CatAbecedarioPageModule' },
  { path: 'cat-animales', loadChildren: './cat-animales/cat-animales.module#CatAnimalesPageModule' },
  { path: 'cat-bebidas', loadChildren: './cat-bebidas/cat-bebidas.module#CatBebidasPageModule' },
  { path: 'cat-colores', loadChildren: './cat-colores/cat-colores.module#CatColoresPageModule' },
  { path: 'cat-comidas', loadChildren: './cat-comidas/cat-comidas.module#CatComidasPageModule' },
  { path: 'cat-departamentos', loadChildren: './cat-departamentos/cat-departamentos.module#CatDepartamentosPageModule' },
  { path: 'cat-emociones', loadChildren: './cat-emociones/cat-emociones.module#CatEmocionesPageModule' },
  { path: 'cat-familia', loadChildren: './cat-familia/cat-familia.module#CatFamiliaPageModule' },
  { path: 'cat-numeros', loadChildren: './cat-numeros/cat-numeros.module#CatNumerosPageModule' },
  { path: 'cat-saludos', loadChildren: './cat-saludos/cat-saludos.module#CatSaludosPageModule' },
  { path: 'letra-a', loadChildren: './letra-a/letra-a.module#LetraAPageModule' },
  { path: 'letra-b', loadChildren: './letra-b/letra-b.module#LetraBPageModule' },
  { path: 'letra-c', loadChildren: './letra-c/letra-c.module#LetraCPageModule' },
  { path: 'letra-ch', loadChildren: './letra-ch/letra-ch.module#LetraChPageModule' },
  { path: 'letra-d', loadChildren: './letra-d/letra-d.module#LetraDPageModule' },
  { path: 'letra-e', loadChildren: './letra-e/letra-e.module#LetraEPageModule' },
  { path: 'letra-f', loadChildren: './letra-f/letra-f.module#LetraFPageModule' },
  { path: 'letra-g', loadChildren: './letra-g/letra-g.module#LetraGPageModule' },
  { path: 'letra-h', loadChildren: './letra-h/letra-h.module#LetraHPageModule' },
  { path: 'letra-i', loadChildren: './letra-i/letra-i.module#LetraIPageModule' },
  { path: 'letra-j', loadChildren: './letra-j/letra-j.module#LetraJPageModule' },
  { path: 'letra-k', loadChildren: './letra-k/letra-k.module#LetraKPageModule' },
  { path: 'letra-l', loadChildren: './letra-l/letra-l.module#LetraLPageModule' },
  { path: 'letra-ll', loadChildren: './letra-ll/letra-ll.module#LetraLlPageModule' },
  { path: 'letra-m', loadChildren: './letra-m/letra-m.module#LetraMPageModule' },
  { path: 'letra-n', loadChildren: './letra-n/letra-n.module#LetraNPageModule' },
  { path: 'letra-n1', loadChildren: './letra-n1/letra-n1.module#LetraN1PageModule' },
  { path: 'letra-o', loadChildren: './letra-o/letra-o.module#LetraOPageModule' },
  { path: 'letra-p', loadChildren: './letra-p/letra-p.module#LetraPPageModule' },
  { path: 'letra-q', loadChildren: './letra-q/letra-q.module#LetraQPageModule' },
  { path: 'letra-r', loadChildren: './letra-r/letra-r.module#LetraRPageModule' },
  { path: 'letra-rr', loadChildren: './letra-rr/letra-rr.module#LetraRrPageModule' },
  { path: 'letra-s', loadChildren: './letra-s/letra-s.module#LetraSPageModule' },
  { path: 'letra-t', loadChildren: './letra-t/letra-t.module#LetraTPageModule' },
  { path: 'letra-u', loadChildren: './letra-u/letra-u.module#LetraUPageModule' },
  { path: 'letra-v', loadChildren: './letra-v/letra-v.module#LetraVPageModule' },
  { path: 'letra-w', loadChildren: './letra-w/letra-w.module#LetraWPageModule' },
  { path: 'letra-x', loadChildren: './letra-x/letra-x.module#LetraXPageModule' },
  { path: 'letra-y', loadChildren: './letra-y/letra-y.module#LetraYPageModule' },
  { path: 'letra-z', loadChildren: './letra-z/letra-z.module#LetraZPageModule' },
  { path: 'num1', loadChildren: './num1/num1.module#Num1PageModule' },
  { path: 'num2', loadChildren: './num2/num2.module#Num2PageModule' },
  { path: 'num3', loadChildren: './num3/num3.module#Num3PageModule' },
  { path: 'num4', loadChildren: './num4/num4.module#Num4PageModule' },
  { path: 'num5', loadChildren: './num5/num5.module#Num5PageModule' },
  { path: 'num6', loadChildren: './num6/num6.module#Num6PageModule' },
  { path: 'num7', loadChildren: './num7/num7.module#Num7PageModule' },
  { path: 'num8', loadChildren: './num8/num8.module#Num8PageModule' },
  { path: 'num9', loadChildren: './num9/num9.module#Num9PageModule' },
  { path: 'num10', loadChildren: './num10/num10.module#Num10PageModule' },
  { path: 'num11', loadChildren: './num11/num11.module#Num11PageModule' },
  { path: 'num12', loadChildren: './num12/num12.module#Num12PageModule' },
  { path: 'num', loadChildren: './num/num.module#NumPageModule' },
  { path: 'num13', loadChildren: './num13/num13.module#Num13PageModule' },
  { path: 'num14', loadChildren: './num14/num14.module#Num14PageModule' },
  { path: 'num15', loadChildren: './num15/num15.module#Num15PageModule' },
  { path: 'num16', loadChildren: './num16/num16.module#Num16PageModule' },
  { path: 'num17', loadChildren: './num17/num17.module#Num17PageModule' },
  { path: 'num18', loadChildren: './num18/num18.module#Num18PageModule' },
  { path: 'num19', loadChildren: './num19/num19.module#Num19PageModule' },
  { path: 'num20', loadChildren: './num20/num20.module#Num20PageModule' },
  { path: 'ani-ardilla', loadChildren: './ani-ardilla/ani-ardilla.module#AniArdillaPageModule' },
  { path: 'ani-caballo', loadChildren: './ani-caballo/ani-caballo.module#AniCaballoPageModule' },
  { path: 'ani-cerdo', loadChildren: './ani-cerdo/ani-cerdo.module#AniCerdoPageModule' },
  { path: 'ani-conejo', loadChildren: './ani-conejo/ani-conejo.module#AniConejoPageModule' },
  { path: 'ani-gallina', loadChildren: './ani-gallina/ani-gallina.module#AniGallinaPageModule' },
  { path: 'ani-gallo', loadChildren: './ani-gallo/ani-gallo.module#AniGalloPageModule' },
  { path: 'ani-gato', loadChildren: './ani-gato/ani-gato.module#AniGatoPageModule' },
  { path: 'ani-mono', loadChildren: './ani-mono/ani-mono.module#AniMonoPageModule' },
  { path: 'ani-perro', loadChildren: './ani-perro/ani-perro.module#AniPerroPageModule' },
  { path: 'ani-vaca', loadChildren: './ani-vaca/ani-vaca.module#AniVacaPageModule' },
  { path: 'registro', loadChildren: './registro/registro.module#RegistroPageModule' },
  { path: 'login', loadChildren: './login/login.module#LoginPageModule' },
  { path: 'beb-cacao', loadChildren: './beb-cacao/beb-cacao.module#BebCacaoPageModule' },
  { path: 'beb-chicha', loadChildren: './beb-chicha/beb-chicha.module#BebChichaPageModule' },
  { path: 'beb-linaza', loadChildren: './beb-linaza/beb-linaza.module#BebLinazaPageModule' },
  { path: 'beb-pinolillo', loadChildren: './beb-pinolillo/beb-pinolillo.module#BebPinolilloPageModule' },
  { path: 'beb-pinol', loadChildren: './beb-pinol/beb-pinol.module#BebPinolPageModule' },
  { path: 'beb-pozol', loadChildren: './beb-pozol/beb-pozol.module#BebPozolPageModule' },
  { path: 'beb-tibio', loadChildren: './beb-tibio/beb-tibio.module#BebTibioPageModule' },
  { path: 'beb-tiste', loadChildren: './beb-tiste/beb-tiste.module#BebTistePageModule' },
  { path: 'beb-chia', loadChildren: './beb-chia/beb-chia.module#BebChiaPageModule' },
  { path: 'beb-jengibre', loadChildren: './beb-jengibre/beb-jengibre.module#BebJengibrePageModule' },
  { path: 'beb-semjicaro', loadChildren: './beb-semjicaro/beb-semjicaro.module#BebSemjicaroPageModule' },
  { path: 'com-baho', loadChildren: './com-baho/com-baho.module#ComBahoPageModule' },
  { path: 'com-asado', loadChildren: './com-asado/com-asado.module#ComAsadoPageModule' },
  { path: 'com-chanyuca', loadChildren: './com-chanyuca/com-chanyuca.module#ComChanyucaPageModule' },
  { path: 'com-gallopinto', loadChildren: './com-gallopinto/com-gallopinto.module#ComGallopintoPageModule' },
  { path: 'com-indioviejo', loadChildren: './com-indioviejo/com-indioviejo.module#ComIndioviejoPageModule' },
  { path: 'com-nacatamal', loadChildren: './com-nacatamal/com-nacatamal.module#ComNacatamalPageModule' },
  { path: 'com-quesillo', loadChildren: './com-quesillo/com-quesillo.module#ComQuesilloPageModule' },
  { path: 'com-rondon', loadChildren: './com-rondon/com-rondon.module#ComRondonPageModule' },
  { path: 'com-sopamond', loadChildren: './com-sopamond/com-sopamond.module#ComSopamondPageModule' },
  { path: 'com-vigoron', loadChildren: './com-vigoron/com-vigoron.module#ComVigoronPageModule' },
  { path: 'dep-boaco', loadChildren: './dep-boaco/dep-boaco.module#DepBoacoPageModule' },
  { path: 'dep-carazo', loadChildren: './dep-carazo/dep-carazo.module#DepCarazoPageModule' },
  { path: 'dep-chinandega', loadChildren: './dep-chinandega/dep-chinandega.module#DepChinandegaPageModule' },
  { path: 'dep-chontales', loadChildren: './dep-chontales/dep-chontales.module#DepChontalesPageModule' },
  { path: 'dep-esteli', loadChildren: './dep-esteli/dep-esteli.module#DepEsteliPageModule' },
  { path: 'dep-granada', loadChildren: './dep-granada/dep-granada.module#DepGranadaPageModule' },
  { path: 'dep-jinotega', loadChildren: './dep-jinotega/dep-jinotega.module#DepJinotegaPageModule' },
  { path: 'dep-leon', loadChildren: './dep-leon/dep-leon.module#DepLeonPageModule' },
  { path: 'dep-madriz', loadChildren: './dep-madriz/dep-madriz.module#DepMadrizPageModule' },
  { path: 'dep-managua', loadChildren: './dep-managua/dep-managua.module#DepManaguaPageModule' },
  { path: 'dep-masaya', loadChildren: './dep-masaya/dep-masaya.module#DepMasayaPageModule' },
  { path: 'dep-matagalpa', loadChildren: './dep-matagalpa/dep-matagalpa.module#DepMatagalpaPageModule' },
  { path: 'dep-nuevaseg', loadChildren: './dep-nuevaseg/dep-nuevaseg.module#DepNuevasegPageModule' },
  { path: 'dep-raccn', loadChildren: './dep-raccn/dep-raccn.module#DepRaccnPageModule' },
  { path: 'dep-raccs', loadChildren: './dep-raccs/dep-raccs.module#DepRaccsPageModule' },
  { path: 'dep-riojuan', loadChildren: './dep-riojuan/dep-riojuan.module#DepRiojuanPageModule' },
  { path: 'dep-rivas', loadChildren: './dep-rivas/dep-rivas.module#DepRivasPageModule' },
  { path: 'emo-amistoso', loadChildren: './emo-amistoso/emo-amistoso.module#EmoAmistosoPageModule' },
  { path: 'emo-cansado', loadChildren: './emo-cansado/emo-cansado.module#EmoCansadoPageModule' },
  { path: 'emo-confundido', loadChildren: './emo-confundido/emo-confundido.module#EmoConfundidoPageModule' },
  { path: 'emo-conmocionado', loadChildren: './emo-conmocionado/emo-conmocionado.module#EmoConmocionadoPageModule' },
  { path: 'emo-enamorado', loadChildren: './emo-enamorado/emo-enamorado.module#EmoEnamoradoPageModule' },
  { path: 'emo-enojado', loadChildren: './emo-enojado/emo-enojado.module#EmoEnojadoPageModule' },
  { path: 'emo-feliz', loadChildren: './emo-feliz/emo-feliz.module#EmoFelizPageModule' },
  { path: 'emo-llorando', loadChildren: './emo-llorando/emo-llorando.module#EmoLlorandoPageModule' },
  { path: 'emo-triste', loadChildren: './emo-triste/emo-triste.module#EmoTristePageModule' },
  { path: 'col-amarillo', loadChildren: './col-amarillo/col-amarillo.module#ColAmarilloPageModule' },
  { path: 'col-azul', loadChildren: './col-azul/col-azul.module#ColAzulPageModule' },
  { path: 'col-blanco', loadChildren: './col-blanco/col-blanco.module#ColBlancoPageModule' },
  { path: 'col-celeste', loadChildren: './col-celeste/col-celeste.module#ColCelestePageModule' },
  { path: 'col-morado', loadChildren: './col-morado/col-morado.module#ColMoradoPageModule' },
  { path: 'col-naranja', loadChildren: './col-naranja/col-naranja.module#ColNaranjaPageModule' },
  { path: 'col-negro', loadChildren: './col-negro/col-negro.module#ColNegroPageModule' },
  { path: 'col-rojo', loadChildren: './col-rojo/col-rojo.module#ColRojoPageModule' },
  { path: 'col-rosado', loadChildren: './col-rosado/col-rosado.module#ColRosadoPageModule' },
  { path: 'col-verde', loadChildren: './col-verde/col-verde.module#ColVerdePageModule' },
  { path: 'fam-abuela', loadChildren: './fam-abuela/fam-abuela.module#FamAbuelaPageModule' },
  { path: 'fam-abuelo', loadChildren: './fam-abuelo/fam-abuelo.module#FamAbueloPageModule' },
  { path: 'fam-hermana', loadChildren: './fam-hermana/fam-hermana.module#FamHermanaPageModule' },
  { path: 'fam-hermano', loadChildren: './fam-hermano/fam-hermano.module#FamHermanoPageModule' },
  { path: 'fam-hija', loadChildren: './fam-hija/fam-hija.module#FamHijaPageModule' },
  { path: 'fam-hijo', loadChildren: './fam-hijo/fam-hijo.module#FamHijoPageModule' },
  { path: 'fam-mama', loadChildren: './fam-mama/fam-mama.module#FamMamaPageModule' },
  { path: 'fam-papa', loadChildren: './fam-papa/fam-papa.module#FamPapaPageModule' },
  { path: 'fam-primos', loadChildren: './fam-primos/fam-primos.module#FamPrimosPageModule' },
  { path: 'fam-tia', loadChildren: './fam-tia/fam-tia.module#FamTiaPageModule' },
  { path: 'fam-tio', loadChildren: './fam-tio/fam-tio.module#FamTioPageModule' },
  { path: 'sal-adios', loadChildren: './sal-adios/sal-adios.module#SalAdiosPageModule' },
  { path: 'sal-buenasnoches', loadChildren: './sal-buenasnoches/sal-buenasnoches.module#SalBuenasnochesPageModule' },
  { path: 'sal-buenastardes', loadChildren: './sal-buenastardes/sal-buenastardes.module#SalBuenastardesPageModule' },
  { path: 'sal-buenosdias', loadChildren: './sal-buenosdias/sal-buenosdias.module#SalBuenosdiasPageModule' },
  { path: 'sal-comoestas', loadChildren: './sal-comoestas/sal-comoestas.module#SalComoestasPageModule' },
  { path: 'sal-compermiso', loadChildren: './sal-compermiso/sal-compermiso.module#SalCompermisoPageModule' },
  { path: 'sal-disculpa', loadChildren: './sal-disculpa/sal-disculpa.module#SalDisculpaPageModule' },
  { path: 'sal-hastapronto', loadChildren: './sal-hastapronto/sal-hastapronto.module#SalHastaprontoPageModule' },
  { path: 'sal-hola', loadChildren: './sal-hola/sal-hola.module#SalHolaPageModule' },
  { path: 'sal-porfavor', loadChildren: './sal-porfavor/sal-porfavor.module#SalPorfavorPageModule' },
  { path: 'chat', loadChildren: './chat/chat.module#ChatPageModule' },
  { path: 'buscador', loadChildren: './buscador/buscador.module#BuscadorPageModule' },
  { path: 'tec', loadChildren: './tec/tec.module#TecPageModule' },  { path: 'cat-deportes', loadChildren: './cat-deportes/cat-deportes.module#CatDeportesPageModule' },
  { path: 'cat-instrumentos', loadChildren: './cat-instrumentos/cat-instrumentos.module#CatInstrumentosPageModule' },
  { path: 'ins-acordeon', loadChildren: './ins-acordeon/ins-acordeon.module#InsAcordeonPageModule' },
  { path: 'ins-flauta', loadChildren: './ins-flauta/ins-flauta.module#InsFlautaPageModule' },
  { path: 'ins-guitarra', loadChildren: './ins-guitarra/ins-guitarra.module#InsGuitarraPageModule' },
  { path: 'ins-piano', loadChildren: './ins-piano/ins-piano.module#InsPianoPageModule' },
  { path: 'ins-violin', loadChildren: './ins-violin/ins-violin.module#InsViolinPageModule' },
  { path: 'depo-baloncesto', loadChildren: './depo-baloncesto/depo-baloncesto.module#DepoBaloncestoPageModule' },
  { path: 'depo-beisbol', loadChildren: './depo-beisbol/depo-beisbol.module#DepoBeisbolPageModule' },
  { path: 'depo-futbol', loadChildren: './depo-futbol/depo-futbol.module#DepoFutbolPageModule' },
  { path: 'depo-natacion', loadChildren: './depo-natacion/depo-natacion.module#DepoNatacionPageModule' },
  { path: 'depo-tenis', loadChildren: './depo-tenis/depo-tenis.module#DepoTenisPageModule' },



];

@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules }), HttpClientModule,
  ], providers: [
    GiphyService,
  ],
  exports: [RouterModule]
})
export class AppRoutingModule { }
